[package]
name = "sftool"
version = "0.1.3"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
sftool-lib = { path = "../sftool-lib" }
strum = {version = "0.27.1",features = ["derive"]}
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
